@echo off
echo Iniciando el Evaluador de Proyectos de la EEBE...
echo Instalando y actualizando librerias necesarias (esto puede tardar unos segundos)...
python -m pip install -r requirements.txt -q
echo Abriendo la aplicacion en el navegador...
python -m streamlit run app.py
pause
